podTemplate(
label: 'sdcclient',
cloud: 'openshift',
containers: [
    containerTemplate(name: 'sdcclient',
                    image: 'stewartshea/sysdig-sdcclient:0.3',
                    resourceLimitMemory: '512Mi',
                    workingDir:'/home/jenkins'
                    )
    ]
    )
{

    node('sdcclient') {
    container('sdcclient')
    {
        stage('Test agent') {
                    environment {
                        SYSDIG_API_TOKEN = credentials('sysdig-api-token')
                        }
                sh 'echo $SYSDIG_API_TOKEN > tokentest'
        
        }
    }
    }
}