podTemplate(
label: 'sdcclient',
cloud: 'openshift',
containers: [
    containerTemplate(name: 'sdcclient',
                    image: 'stewartshea/sysdig-sdcclient:0.10',
                    resourceLimitMemory: '512Mi',
                    workingDir:'/home/jenkins'
                    )
    ]
    )
{

    node('sdcclient') {
        // environment {
        //     SYSDIG_API_TOKEN = credentials('sysdig-api-token')
        //     }
    container('sdcclient')
    {
        stage('Generate Python Scripts') {
        withCredentials([string(credentialsId: 'sysdig-api-token', variable: 'SYSDIG_API_TOKEN')]) {

                sh 'ansible-playbook /ansible/template-machine.yml'
        }
        }
        stage('Update Teams') {
        withCredentials([string(credentialsId: 'sysdig-api-token', variable: 'SYSDIG_API_TOKEN')]) {

                sh 'python /ansible/team_mgmt.py'
        }
        }
        // stage('Update Dashboards') {
        // withCredentials([string(credentialsId: 'sysdig-api-token', variable: 'SYSDIG_API_TOKEN')]) {

        //         sh 'python /ansible/dashboards.py'
        // }
        // }
        // stage('Update Alerts') {
        // withCredentials([string(credentialsId: 'sysdig-api-token', variable: 'SYSDIG_API_TOKEN')]) {

        //         sh 'python /ansible/alerts.py'
        // }
        // }
    }
    }
}