---
- name: Generate Terraform File
  hosts: localhost
  connection: local
  vars_files: 
    - vars.yml
  tasks: 
    - name: Render team templates
      template: 
        src: team_mgmt.py.j2
        dest: ../sysdig/team_mgmt.py
        backup: no
